<?php
/**
 * ApiErrorCodeType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ApiErrorCodeType Class Doc Comment
 *
 * @category Class
 * @description Типизированный код ошибки. Описания возможных значений приведены в разделе [Коды ошибок](../../concepts/error-codes.md).
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApiErrorCodeType
{
    /**
     * Possible values of this enum
     */
    public const INVALID_FEED_ID = 'INVALID_FEED_ID';

    public const INVALID_WAREHOUSE_ID = 'INVALID_WAREHOUSE_ID';

    public const GROUPED_WAREHOUSE = 'GROUPED_WAREHOUSE';

    public const DUPLICATE_OFFER = 'DUPLICATE_OFFER';

    public const INVALID_TTL = 'INVALID_TTL';

    public const INVALID_COMMENT = 'INVALID_COMMENT';

    public const LIMIT_EXCEEDED = 'LIMIT_EXCEEDED';

    public const NON_POSITIVE_LIMIT = 'NON_POSITIVE_LIMIT';

    public const REQUEST_LIMIT_EXCEEDED = 'REQUEST_LIMIT_EXCEEDED';

    public const INVALID_OFFER_ID = 'INVALID_OFFER_ID';

    public const MISSING_OFFER_ID = 'MISSING_OFFER_ID';

    public const MISSING_OFFER = 'MISSING_OFFER';

    public const INVALID_SHOP_SKU = 'INVALID_SHOP_SKU';

    public const AMBIGUOUS_OFFER = 'AMBIGUOUS_OFFER';

    public const OFFER_NOT_FOUND = 'OFFER_NOT_FOUND';

    public const MODEL_NOT_FOUND = 'MODEL_NOT_FOUND';

    public const CATEGORY_NOT_FOUND = 'CATEGORY_NOT_FOUND';

    public const NO_REQUIRED_FIELDS = 'NO_REQUIRED_FIELDS';

    public const FORBIDDEN_FIELD_DEFINITION = 'FORBIDDEN_FIELD_DEFINITION';

    public const PROBLEMS_IN_OTHER_OFFERS = 'PROBLEMS_IN_OTHER_OFFERS';

    public const AMBIGUOUS_FIELD_DEFINITION = 'AMBIGUOUS_FIELD_DEFINITION';

    public const INVALID_OUTLET_INFO = 'INVALID_OUTLET_INFO';

    public const DUPLICATE_OUTLET_CODE = 'DUPLICATE_OUTLET_CODE';

    public const UNKNOWN_REGION = 'UNKNOWN_REGION';

    public const WRONG_REGION = 'WRONG_REGION';

    public const NOT_SPECIFIED = 'NOT_SPECIFIED';

    public const INVALID_PHONE_FORMAT = 'INVALID_PHONE_FORMAT';

    public const INVALID_TIME_FORMAT = 'INVALID_TIME_FORMAT';

    public const COULD_NOT_FIND_COORDS = 'COULD_NOT_FIND_COORDS';

    public const WRONG_OUTLET_GPS_COORDINATES = 'WRONG_OUTLET_GPS_COORDINATES';

    public const ITEM_NOT_FOUND = 'ITEM_NOT_FOUND';

    public const INVALID_ITEM = 'INVALID_ITEM';

    public const ITEM_DUPLICATE = 'ITEM_DUPLICATE';

    public const ITEM_SHIPPED = 'ITEM_SHIPPED';

    public const ITEMS_ADDITION_NOT_SUPPORTED = 'ITEMS_ADDITION_NOT_SUPPORTED';

    public const CANNOT_REMOVE_LAST_ITEM = 'CANNOT_REMOVE_LAST_ITEM';

    public const OTHER_REMOVE_ITEM_ERROR = 'OTHER_REMOVE_ITEM_ERROR';

    public const TRACK_CODE_ALREADY_USED = 'TRACK_CODE_ALREADY_USED';

    public const TOO_MANY_CISES_FOR_ITEM = 'TOO_MANY_CISES_FOR_ITEM';

    public const TOO_FEW_CISES_FOR_ITEM = 'TOO_FEW_CISES_FOR_ITEM';

    public const INVALID_CIS = 'INVALID_CIS';

    public const DUPLICATE_CIS = 'DUPLICATE_CIS';

    public const TOO_MANY_UINS_FOR_ITEM = 'TOO_MANY_UINS_FOR_ITEM';

    public const TOO_FEW_UINS_FOR_ITEM = 'TOO_FEW_UINS_FOR_ITEM';

    public const INVALID_UIN = 'INVALID_UIN';

    public const UIN_VALIDATION_IN_PROGRESS_ERROR = 'UIN_VALIDATION_IN_PROGRESS_ERROR';

    public const CIS_VALIDATION_IN_PROGRESS_ERROR = 'CIS_VALIDATION_IN_PROGRESS_ERROR';

    public const INVALID_RNPT = 'INVALID_RNPT';

    public const INVALID_GTD = 'INVALID_GTD';

    public const INVALID_COUNTRY_CODE = 'INVALID_COUNTRY_CODE';

    public const COUNTRY_CODE_AND_GTD_ARE_REQUIRED_VALIDATION_ERROR = 'COUNTRY_CODE_AND_GTD_ARE_REQUIRED_VALIDATION_ERROR';

    public const DUPLICATE_UIN = 'DUPLICATE_UIN';

    public const DELETED_ITEMS_EXCEEDS_THRESHOLD = 'DELETED_ITEMS_EXCEEDS_THRESHOLD';

    public const PROMO_PROHIBITS_DELETE = 'PROMO_PROHIBITS_DELETE';

    public const PAYMENT_PROHIBITS_DELETE = 'PAYMENT_PROHIBITS_DELETE';

    public const CANCELLATION_REQUESTED = 'CANCELLATION_REQUESTED';

    public const ORDER_IN_TERMINAL_STATE = 'ORDER_IN_TERMINAL_STATE';

    public const EDIT_COUNT_EXCEEDED = 'EDIT_COUNT_EXCEEDED';

    public const DAYS_COUNT_EXCEEDED = 'DAYS_COUNT_EXCEEDED';

    public const SAME_DELIVERY_DATES = 'SAME_DELIVERY_DATES';

    public const INCORRECT_INN = 'INCORRECT_INN';

    public const BAD_REQUEST = 'BAD_REQUEST';

    public const UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE';

    public const FORBIDDEN = 'FORBIDDEN';

    public const NOT_FOUND = 'NOT_FOUND';

    public const LOCKED = 'LOCKED';

    public const CONSTRAINT_VIOLATION = 'CONSTRAINT_VIOLATION';

    public const DUPLICATE_MARKET_SKU = 'DUPLICATE_MARKET_SKU';

    public const INVALID_MARKET_SKU = 'INVALID_MARKET_SKU';

    public const INVALID_MAPPING = 'INVALID_MAPPING';

    public const MISSING_MAPPING = 'MISSING_MAPPING';

    public const UNKNOWN_PARAMETER = 'UNKNOWN_PARAMETER';

    public const INTERNAL_ERROR = 'INTERNAL_ERROR';

    public const MISSING_PARAM = 'MISSING_PARAM';

    public const DUPLICATE_SHOP_SKU = 'DUPLICATE_SHOP_SKU';

    public const INVALID_CURRENCY = 'INVALID_CURRENCY';

    public const INVALID_PAYMENT_SETTINGS = 'INVALID_PAYMENT_SETTINGS';

    public const OTHER = 'OTHER';

    public const INVALID_CATEGORY = 'INVALID_CATEGORY';

    public const INVALID_QUERY_PARAMETER = 'INVALID_QUERY_PARAMETER';

    public const CAMPAIGN_NOT_FOUND = 'CAMPAIGN_NOT_FOUND';

    public const PARTNER_NOT_FOUND = 'PARTNER_NOT_FOUND';

    public const BUSINESS_NOT_FOUND = 'BUSINESS_NOT_FOUND';

    public const CAMPAIGN_TYPE_NOT_SUPPORTED = 'CAMPAIGN_TYPE_NOT_SUPPORTED';

    public const BAD_OFFERS = 'BAD_OFFERS';

    public const ALREADY_CONFIRMED = 'ALREADY_CONFIRMED';

    public const CUTOFF_NOT_REACHED = 'CUTOFF_NOT_REACHED';

    public const NO_ORDERS = 'NO_ORDERS';

    public const BAD_ORDERS = 'BAD_ORDERS';

    public const NO_BOXES = 'NO_BOXES';

    public const INVALID_ORDER_BEFORE = 'INVALID_ORDER_BEFORE';

    public const STATUS_NOT_ALLOWED = 'STATUS_NOT_ALLOWED';

    public const SUBSTATUS_NOT_ALLOWED = 'SUBSTATUS_NOT_ALLOWED';

    public const USER_UNREACHABLE_NOT_ALLOWED = 'USER_UNREACHABLE_NOT_ALLOWED';

    public const ACTION_FORBIDDEN = 'ACTION_FORBIDDEN';

    public const CANT_DELIVER_ORDER_TO_ADDRESS = 'CANT_DELIVER_ORDER_TO_ADDRESS';

    public const PICKUP_EXPIRED_CANCELLATION_FORBIDDEN = 'PICKUP_EXPIRED_CANCELLATION_FORBIDDEN';

    public const INVALID_ORDER_STATUS = 'INVALID_ORDER_STATUS';

    public const CODE_NEED_BE_REFRESHED = 'CODE_NEED_BE_REFRESHED';

    public const CODE_ALREADY_ACCEPTED = 'CODE_ALREADY_ACCEPTED';

    public const NO_EMAIL = 'NO_EMAIL';

    public const PROMO_ENDED = 'PROMO_ENDED';

    public const PROMO_ENTRY_DEADLINE_EXCEEDED = 'PROMO_ENTRY_DEADLINE_EXCEEDED';

    public const PROMO_MECHANICS_NOT_SUPPORTED = 'PROMO_MECHANICS_NOT_SUPPORTED';

    public const PROMO_SINGLE_OFFER_TASK_LIMIT_EXCEEDED = 'PROMO_SINGLE_OFFER_TASK_LIMIT_EXCEEDED';

    public const SUPPLY_REQUEST_NOT_FOUND = 'SUPPLY_REQUEST_NOT_FOUND';

    public const DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND';

    public const EXTERNAL_ORDER_ID_UPDATE_ERROR = 'EXTERNAL_ORDER_ID_UPDATE_ERROR';

    public const DECLINE_REASON_ARE_REQUIRED_ERROR = 'DECLINE_REASON_ARE_REQUIRED_ERROR';

    public const CONTRACT_NOT_FOUND = 'CONTRACT_NOT_FOUND';

    public const CONTRACT_WITH_AGENCY = 'CONTRACT_WITH_AGENCY';

    public const NOT_ENOUGH_STOCK = 'NOT_ENOUGH_STOCK';

    public const INVALID_DELIVERY_OPTION = 'INVALID_DELIVERY_OPTION';

    public const ORDER_ALREADY_EXISTS = 'ORDER_ALREADY_EXISTS';

    public const ORDER_MODIFICATION_NOT_ALLOWED = 'ORDER_MODIFICATION_NOT_ALLOWED';

    public const DELIVERY_TAX_INFO_NO_DBS_PARTNER = 'DELIVERY_TAX_INFO_NO_DBS_PARTNER';

    public const DELIVERY_TAX_INFO_INCORRECT_ORDER_STATUS = 'DELIVERY_TAX_INFO_INCORRECT_ORDER_STATUS';

    public const DELIVERY_TAX_INFO_TAX_SYSTEM_IS_NOT_SUPPORTED = 'DELIVERY_TAX_INFO_TAX_SYSTEM_IS_NOT_SUPPORTED';

    public const DELIVERY_TAX_INFO_INCORRECT_DELIVERY_SERVICE = 'DELIVERY_TAX_INFO_INCORRECT_DELIVERY_SERVICE';

    public const DELIVERY_TAX_INFO_INCORRECT_REQUEST = 'DELIVERY_TAX_INFO_INCORRECT_REQUEST';

    public const RETURN_ALREADY_EXISTS = 'RETURN_ALREADY_EXISTS';

    public const INVALID_RETURN_OFFERS = 'INVALID_RETURN_OFFERS';

    public const PHOTO_UPLOAD_FAILED = 'PHOTO_UPLOAD_FAILED';

    public const INVALID_DELIVERY_TYPE = 'INVALID_DELIVERY_TYPE';

    public const INVALID_RETURN_REASON = 'INVALID_RETURN_REASON';

    public const INVALID_ITEM_DIMENSIONS = 'INVALID_ITEM_DIMENSIONS';

    public const API_DISABLED = 'API_DISABLED';

    public const RESTRICTED_BY_MARKETPLACE_REGION = 'RESTRICTED_BY_MARKETPLACE_REGION';

    public const NO_ACCESS_BY_DEPRECATION_POLICY = 'NO_ACCESS_BY_DEPRECATION_POLICY';

    public const ORDER_EDIT_ERROR = 'ORDER_EDIT_ERROR';

    public const ADVERTISER_STATUS_MISMATCH = 'ADVERTISER_STATUS_MISMATCH';

    public const RESTRICTED_FOR_ADVERTISER = 'RESTRICTED_FOR_ADVERTISER';

    public const SUBSCRIPTION_REQUIRED = 'SUBSCRIPTION_REQUIRED';

    public const CIS_HANDLE_MODE_RESTRICTION = 'CIS_HANDLE_MODE_RESTRICTION';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::INVALID_FEED_ID,
            self::INVALID_WAREHOUSE_ID,
            self::GROUPED_WAREHOUSE,
            self::DUPLICATE_OFFER,
            self::INVALID_TTL,
            self::INVALID_COMMENT,
            self::LIMIT_EXCEEDED,
            self::NON_POSITIVE_LIMIT,
            self::REQUEST_LIMIT_EXCEEDED,
            self::INVALID_OFFER_ID,
            self::MISSING_OFFER_ID,
            self::MISSING_OFFER,
            self::INVALID_SHOP_SKU,
            self::AMBIGUOUS_OFFER,
            self::OFFER_NOT_FOUND,
            self::MODEL_NOT_FOUND,
            self::CATEGORY_NOT_FOUND,
            self::NO_REQUIRED_FIELDS,
            self::FORBIDDEN_FIELD_DEFINITION,
            self::PROBLEMS_IN_OTHER_OFFERS,
            self::AMBIGUOUS_FIELD_DEFINITION,
            self::INVALID_OUTLET_INFO,
            self::DUPLICATE_OUTLET_CODE,
            self::UNKNOWN_REGION,
            self::WRONG_REGION,
            self::NOT_SPECIFIED,
            self::INVALID_PHONE_FORMAT,
            self::INVALID_TIME_FORMAT,
            self::COULD_NOT_FIND_COORDS,
            self::WRONG_OUTLET_GPS_COORDINATES,
            self::ITEM_NOT_FOUND,
            self::INVALID_ITEM,
            self::ITEM_DUPLICATE,
            self::ITEM_SHIPPED,
            self::ITEMS_ADDITION_NOT_SUPPORTED,
            self::CANNOT_REMOVE_LAST_ITEM,
            self::OTHER_REMOVE_ITEM_ERROR,
            self::TRACK_CODE_ALREADY_USED,
            self::TOO_MANY_CISES_FOR_ITEM,
            self::TOO_FEW_CISES_FOR_ITEM,
            self::INVALID_CIS,
            self::DUPLICATE_CIS,
            self::TOO_MANY_UINS_FOR_ITEM,
            self::TOO_FEW_UINS_FOR_ITEM,
            self::INVALID_UIN,
            self::UIN_VALIDATION_IN_PROGRESS_ERROR,
            self::CIS_VALIDATION_IN_PROGRESS_ERROR,
            self::INVALID_RNPT,
            self::INVALID_GTD,
            self::INVALID_COUNTRY_CODE,
            self::COUNTRY_CODE_AND_GTD_ARE_REQUIRED_VALIDATION_ERROR,
            self::DUPLICATE_UIN,
            self::DELETED_ITEMS_EXCEEDS_THRESHOLD,
            self::PROMO_PROHIBITS_DELETE,
            self::PAYMENT_PROHIBITS_DELETE,
            self::CANCELLATION_REQUESTED,
            self::ORDER_IN_TERMINAL_STATE,
            self::EDIT_COUNT_EXCEEDED,
            self::DAYS_COUNT_EXCEEDED,
            self::SAME_DELIVERY_DATES,
            self::INCORRECT_INN,
            self::BAD_REQUEST,
            self::UNSUPPORTED_MEDIA_TYPE,
            self::FORBIDDEN,
            self::NOT_FOUND,
            self::LOCKED,
            self::CONSTRAINT_VIOLATION,
            self::DUPLICATE_MARKET_SKU,
            self::INVALID_MARKET_SKU,
            self::INVALID_MAPPING,
            self::MISSING_MAPPING,
            self::UNKNOWN_PARAMETER,
            self::INTERNAL_ERROR,
            self::MISSING_PARAM,
            self::DUPLICATE_SHOP_SKU,
            self::INVALID_CURRENCY,
            self::INVALID_PAYMENT_SETTINGS,
            self::OTHER,
            self::INVALID_CATEGORY,
            self::INVALID_QUERY_PARAMETER,
            self::CAMPAIGN_NOT_FOUND,
            self::PARTNER_NOT_FOUND,
            self::BUSINESS_NOT_FOUND,
            self::CAMPAIGN_TYPE_NOT_SUPPORTED,
            self::BAD_OFFERS,
            self::ALREADY_CONFIRMED,
            self::CUTOFF_NOT_REACHED,
            self::NO_ORDERS,
            self::BAD_ORDERS,
            self::NO_BOXES,
            self::INVALID_ORDER_BEFORE,
            self::STATUS_NOT_ALLOWED,
            self::SUBSTATUS_NOT_ALLOWED,
            self::USER_UNREACHABLE_NOT_ALLOWED,
            self::ACTION_FORBIDDEN,
            self::CANT_DELIVER_ORDER_TO_ADDRESS,
            self::PICKUP_EXPIRED_CANCELLATION_FORBIDDEN,
            self::INVALID_ORDER_STATUS,
            self::CODE_NEED_BE_REFRESHED,
            self::CODE_ALREADY_ACCEPTED,
            self::NO_EMAIL,
            self::PROMO_ENDED,
            self::PROMO_ENTRY_DEADLINE_EXCEEDED,
            self::PROMO_MECHANICS_NOT_SUPPORTED,
            self::PROMO_SINGLE_OFFER_TASK_LIMIT_EXCEEDED,
            self::SUPPLY_REQUEST_NOT_FOUND,
            self::DOCUMENT_NOT_FOUND,
            self::EXTERNAL_ORDER_ID_UPDATE_ERROR,
            self::DECLINE_REASON_ARE_REQUIRED_ERROR,
            self::CONTRACT_NOT_FOUND,
            self::CONTRACT_WITH_AGENCY,
            self::NOT_ENOUGH_STOCK,
            self::INVALID_DELIVERY_OPTION,
            self::ORDER_ALREADY_EXISTS,
            self::ORDER_MODIFICATION_NOT_ALLOWED,
            self::DELIVERY_TAX_INFO_NO_DBS_PARTNER,
            self::DELIVERY_TAX_INFO_INCORRECT_ORDER_STATUS,
            self::DELIVERY_TAX_INFO_TAX_SYSTEM_IS_NOT_SUPPORTED,
            self::DELIVERY_TAX_INFO_INCORRECT_DELIVERY_SERVICE,
            self::DELIVERY_TAX_INFO_INCORRECT_REQUEST,
            self::RETURN_ALREADY_EXISTS,
            self::INVALID_RETURN_OFFERS,
            self::PHOTO_UPLOAD_FAILED,
            self::INVALID_DELIVERY_TYPE,
            self::INVALID_RETURN_REASON,
            self::INVALID_ITEM_DIMENSIONS,
            self::API_DISABLED,
            self::RESTRICTED_BY_MARKETPLACE_REGION,
            self::NO_ACCESS_BY_DEPRECATION_POLICY,
            self::ORDER_EDIT_ERROR,
            self::ADVERTISER_STATUS_MISMATCH,
            self::RESTRICTED_FOR_ADVERTISER,
            self::SUBSCRIPTION_REQUIRED,
            self::CIS_HANDLE_MODE_RESTRICTION
        ];
    }
}


