<?php
/**
 * BusinessSubscriptionLevelType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * BusinessSubscriptionLevelType Class Doc Comment
 *
 * @category Class
 * @description Уровень подписки кабинета:  * &#x60;NONE&#x60; — подписка отсутствует. * &#x60;LIGHT&#x60; — уровень подписки Лайт. * &#x60;MEDIUM&#x60; — уровень подписки Медиум.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class BusinessSubscriptionLevelType
{
    /**
     * Possible values of this enum
     */
    public const NONE = 'NONE';

    public const LIGHT = 'LIGHT';

    public const MEDIUM = 'MEDIUM';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NONE,
            self::LIGHT,
            self::MEDIUM
        ];
    }
}


