<?php
/**
 * ChatContextType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ChatContextType Class Doc Comment
 *
 * @category Class
 * @description Тип чата:  * &#x60;ORDER&#x60; — по заказам. Подробнее о чатах по заказам читайте в [Справке Маркета для продавцов](https://yandex.ru/support/marketplace/ru/orders/communication/about-orders). * &#x60;RETURN&#x60; — по возвратам (:no-translate[FBS] и Экспресс). Подробнее о чатах по возвратам читайте в [Справке Маркета для продавцов](https://yandex.ru/support/marketplace/ru/orders/communication/about-orders). * &#x60;DIRECT&#x60; — чат, который начал покупатель. Подробнее о таком типе читайте в [Справке Маркета для продавцов](https://yandex.ru/support/marketplace/ru/orders/communication/with-users).
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ChatContextType
{
    /**
     * Possible values of this enum
     */
    public const ORDER = 'ORDER';

    public const _RETURN = 'RETURN';

    public const DIRECT = 'DIRECT';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ORDER,
            self::_RETURN,
            self::DIRECT
        ];
    }
}


