<?php
/**
 * DigitalGoodsDeliveryType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DigitalGoodsDeliveryType Class Doc Comment
 *
 * @category Class
 * @description Способ получения цифрового товара:  * &#x60;EMAIL&#x60; — код активации по почте: покупатель получит письмо с кодом и инструкцией на почту.  * &#x60;ACTIVATION_CODE&#x60; — код активации в заказе на Маркете: покупатель получит инструкцию и код в чате с магазином, а в списке заказов сможет скопировать код.  * &#x60;STEAM_GIFT&#x60; — игры подарком в Steam: вы получите от покупателя ссылку формата https://s.team/p/m**-***_/_******** на добавление в друзья. Перейдите по ссылке, добавьте покупателя в друзья и отправьте ему игру. В течение трех часов передайте Маркету статус, что заказ доставлен — через API или на странице заказа.  * &#x60;CHAT&#x60; — игры и товары в чате с покупателем на Маркете: покупатель получит сертификат в чате с магазином. Передайте Маркету статус, что заказ доставлен — через API или на странице заказа.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DigitalGoodsDeliveryType
{
    /**
     * Possible values of this enum
     */
    public const EMAIL = 'EMAIL';

    public const ACTIVATION_CODE = 'ACTIVATION_CODE';

    public const STEAM_GIFT = 'STEAM_GIFT';

    public const CHAT = 'CHAT';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::EMAIL,
            self::ACTIVATION_CODE,
            self::STEAM_GIFT,
            self::CHAT
        ];
    }
}


