<?php
/**
 * DocumentType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DocumentType Class Doc Comment
 *
 * @category Class
 * @description Тип документа:  * &#x60;CONFORMITY_DECLARATION&#x60; — Декларация о соответствии. * &#x60;CONFORMITY_CERTIFICATE&#x60; — Сертификат соответствия. * &#x60;STATE_REGISTRATION_CERTIFICATE&#x60; — Государственная регистрация продукции (санэпид требования). * &#x60;MEDICINAL_PRODUCT_CERTIFICATE&#x60; — Обязательные документы для аптеки. * &#x60;BIOLOGICALLY_ACTIVE_ADDITIVE_CERTIFICATE&#x60; — Свидетельство о государственной регистрации БАД. * &#x60;MEDICAL_DEVICE_CERTIFICATE&#x60; — Регистрационное удостоверение медицинского изделия. * &#x60;AGROCHEMICAL_PESTICIDE_CERTIFICATE&#x60; — Государственная регистрация пестицида и агрохимиката.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentType
{
    /**
     * Possible values of this enum
     */
    public const CONFORMITY_DECLARATION = 'CONFORMITY_DECLARATION';

    public const CONFORMITY_CERTIFICATE = 'CONFORMITY_CERTIFICATE';

    public const STATE_REGISTRATION_CERTIFICATE = 'STATE_REGISTRATION_CERTIFICATE';

    public const MEDICINAL_PRODUCT_CERTIFICATE = 'MEDICINAL_PRODUCT_CERTIFICATE';

    public const BIOLOGICALLY_ACTIVE_ADDITIVE_CERTIFICATE = 'BIOLOGICALLY_ACTIVE_ADDITIVE_CERTIFICATE';

    public const MEDICAL_DEVICE_CERTIFICATE = 'MEDICAL_DEVICE_CERTIFICATE';

    public const AGROCHEMICAL_PESTICIDE_CERTIFICATE = 'AGROCHEMICAL_PESTICIDE_CERTIFICATE';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CONFORMITY_DECLARATION,
            self::CONFORMITY_CERTIFICATE,
            self::STATE_REGISTRATION_CERTIFICATE,
            self::MEDICINAL_PRODUCT_CERTIFICATE,
            self::BIOLOGICALLY_ACTIVE_ADDITIVE_CERTIFICATE,
            self::MEDICAL_DEVICE_CERTIFICATE,
            self::AGROCHEMICAL_PESTICIDE_CERTIFICATE
        ];
    }
}


