<?php
/**
 * DocumentErrorCodeType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DocumentErrorCodeType Class Doc Comment
 *
 * @category Class
 * @description Код ошибки документа:  * &#x60;DOCUMENT_VALIDATION_FAILED&#x60; — документ не прошел проверку. * &#x60;DOCUMENT_ALREADY_EXISTS&#x60; — документ уже существует. * &#x60;DOCUMENT_NOT_FOUND&#x60; — документ не найден. * &#x60;DOCUMENT_UPDATE_NOT_ALLOWED&#x60; — изменение документа запрещено. * &#x60;DOCUMENT_CONCURRENT_MODIFICATION&#x60; — документ был изменен параллельно.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentErrorCodeType
{
    /**
     * Possible values of this enum
     */
    public const DOCUMENT_VALIDATION_FAILED = 'DOCUMENT_VALIDATION_FAILED';

    public const DOCUMENT_ALREADY_EXISTS = 'DOCUMENT_ALREADY_EXISTS';

    public const DOCUMENT_NOT_FOUND = 'DOCUMENT_NOT_FOUND';

    public const DOCUMENT_UPDATE_NOT_ALLOWED = 'DOCUMENT_UPDATE_NOT_ALLOWED';

    public const DOCUMENT_CONCURRENT_MODIFICATION = 'DOCUMENT_CONCURRENT_MODIFICATION';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::DOCUMENT_VALIDATION_FAILED,
            self::DOCUMENT_ALREADY_EXISTS,
            self::DOCUMENT_NOT_FOUND,
            self::DOCUMENT_UPDATE_NOT_ALLOWED,
            self::DOCUMENT_CONCURRENT_MODIFICATION
        ];
    }
}


