<?php
/**
 * DocumentStatusType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * DocumentStatusType Class Doc Comment
 *
 * @category Class
 * @description Статус документа:  * &#x60;ACTIVE&#x60; — действует. * &#x60;NOT_FOUND&#x60; — не найден в реестре. * &#x60;VALIDATING&#x60; — проверяется. * &#x60;WAITING_FIXES&#x60; — ожидает исправлений. * &#x60;EXPIRED&#x60; — срок действия истек. * &#x60;REVOKED&#x60; — отозван.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DocumentStatusType
{
    /**
     * Possible values of this enum
     */
    public const ACTIVE = 'ACTIVE';

    public const NOT_FOUND = 'NOT_FOUND';

    public const VALIDATING = 'VALIDATING';

    public const WAITING_FIXES = 'WAITING_FIXES';

    public const EXPIRED = 'EXPIRED';

    public const REVOKED = 'REVOKED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::ACTIVE,
            self::NOT_FOUND,
            self::VALIDATING,
            self::WAITING_FIXES,
            self::EXPIRED,
            self::REVOKED
        ];
    }
}


