<?php
/**
 * GetBusinessOrdersRequest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * GetBusinessOrdersRequest Class Doc Comment
 *
 * @category Class
 * @description Запрос на получение информации о заказах бизнеса.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class GetBusinessOrdersRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'GetBusinessOrdersRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'order_ids' => 'int[]',
        'external_order_ids' => 'string[]',
        'program_types' => '\OpenAPI\Client\Model\SellingProgramType[]',
        'campaign_ids' => 'int[]',
        'statuses' => '\OpenAPI\Client\Model\OrderStatusType[]',
        'substatuses' => '\OpenAPI\Client\Model\OrderSubstatusType[]',
        'dates' => '\OpenAPI\Client\Model\OrderDatesFilterDTO',
        'fake' => 'bool',
        'waiting_for_cancellation_approve' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'order_ids' => 'int64',
        'external_order_ids' => null,
        'program_types' => null,
        'campaign_ids' => 'int64',
        'statuses' => null,
        'substatuses' => null,
        'dates' => null,
        'fake' => null,
        'waiting_for_cancellation_approve' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'order_ids' => true,
        'external_order_ids' => true,
        'program_types' => true,
        'campaign_ids' => true,
        'statuses' => true,
        'substatuses' => true,
        'dates' => false,
        'fake' => false,
        'waiting_for_cancellation_approve' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'order_ids' => 'orderIds',
        'external_order_ids' => 'externalOrderIds',
        'program_types' => 'programTypes',
        'campaign_ids' => 'campaignIds',
        'statuses' => 'statuses',
        'substatuses' => 'substatuses',
        'dates' => 'dates',
        'fake' => 'fake',
        'waiting_for_cancellation_approve' => 'waitingForCancellationApprove'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'order_ids' => 'setOrderIds',
        'external_order_ids' => 'setExternalOrderIds',
        'program_types' => 'setProgramTypes',
        'campaign_ids' => 'setCampaignIds',
        'statuses' => 'setStatuses',
        'substatuses' => 'setSubstatuses',
        'dates' => 'setDates',
        'fake' => 'setFake',
        'waiting_for_cancellation_approve' => 'setWaitingForCancellationApprove'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'order_ids' => 'getOrderIds',
        'external_order_ids' => 'getExternalOrderIds',
        'program_types' => 'getProgramTypes',
        'campaign_ids' => 'getCampaignIds',
        'statuses' => 'getStatuses',
        'substatuses' => 'getSubstatuses',
        'dates' => 'getDates',
        'fake' => 'getFake',
        'waiting_for_cancellation_approve' => 'getWaitingForCancellationApprove'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('order_ids', $data ?? [], null);
        $this->setIfExists('external_order_ids', $data ?? [], null);
        $this->setIfExists('program_types', $data ?? [], null);
        $this->setIfExists('campaign_ids', $data ?? [], null);
        $this->setIfExists('statuses', $data ?? [], null);
        $this->setIfExists('substatuses', $data ?? [], null);
        $this->setIfExists('dates', $data ?? [], null);
        $this->setIfExists('fake', $data ?? [], null);
        $this->setIfExists('waiting_for_cancellation_approve', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['order_ids']) && (count($this->container['order_ids']) > 50)) {
            $invalidProperties[] = "invalid value for 'order_ids', number of items must be less than or equal to 50.";
        }

        if (!is_null($this->container['order_ids']) && (count($this->container['order_ids']) < 1)) {
            $invalidProperties[] = "invalid value for 'order_ids', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['external_order_ids']) && (count($this->container['external_order_ids']) > 50)) {
            $invalidProperties[] = "invalid value for 'external_order_ids', number of items must be less than or equal to 50.";
        }

        if (!is_null($this->container['external_order_ids']) && (count($this->container['external_order_ids']) < 1)) {
            $invalidProperties[] = "invalid value for 'external_order_ids', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['program_types']) && (count($this->container['program_types']) < 1)) {
            $invalidProperties[] = "invalid value for 'program_types', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['campaign_ids']) && (count($this->container['campaign_ids']) > 50)) {
            $invalidProperties[] = "invalid value for 'campaign_ids', number of items must be less than or equal to 50.";
        }

        if (!is_null($this->container['campaign_ids']) && (count($this->container['campaign_ids']) < 1)) {
            $invalidProperties[] = "invalid value for 'campaign_ids', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['statuses']) && (count($this->container['statuses']) < 1)) {
            $invalidProperties[] = "invalid value for 'statuses', number of items must be greater than or equal to 1.";
        }

        if (!is_null($this->container['substatuses']) && (count($this->container['substatuses']) < 1)) {
            $invalidProperties[] = "invalid value for 'substatuses', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets order_ids
     *
     * @return int[]|null
     */
    public function getOrderIds()
    {
        return $this->container['order_ids'];
    }

    /**
     * Sets order_ids
     *
     * @param int[]|null $order_ids Идентификаторы заказов.
     *
     * @return self
     */
    public function setOrderIds($order_ids)
    {
        if (is_null($order_ids)) {
            array_push($this->openAPINullablesSetToNull, 'order_ids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('order_ids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($order_ids) && (count($order_ids) > 50)) {
            throw new \InvalidArgumentException('invalid value for $order_ids when calling GetBusinessOrdersRequest., number of items must be less than or equal to 50.');
        }
        if (!is_null($order_ids) && (count($order_ids) < 1)) {
            throw new \InvalidArgumentException('invalid length for $order_ids when calling GetBusinessOrdersRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['order_ids'] = $order_ids;

        return $this;
    }

    /**
     * Gets external_order_ids
     *
     * @return string[]|null
     */
    public function getExternalOrderIds()
    {
        return $this->container['external_order_ids'];
    }

    /**
     * Sets external_order_ids
     *
     * @param string[]|null $external_order_ids Внешние идентификаторы заказов.
     *
     * @return self
     */
    public function setExternalOrderIds($external_order_ids)
    {
        if (is_null($external_order_ids)) {
            array_push($this->openAPINullablesSetToNull, 'external_order_ids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('external_order_ids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($external_order_ids) && (count($external_order_ids) > 50)) {
            throw new \InvalidArgumentException('invalid value for $external_order_ids when calling GetBusinessOrdersRequest., number of items must be less than or equal to 50.');
        }
        if (!is_null($external_order_ids) && (count($external_order_ids) < 1)) {
            throw new \InvalidArgumentException('invalid length for $external_order_ids when calling GetBusinessOrdersRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['external_order_ids'] = $external_order_ids;

        return $this;
    }

    /**
     * Gets program_types
     *
     * @return \OpenAPI\Client\Model\SellingProgramType[]|null
     */
    public function getProgramTypes()
    {
        return $this->container['program_types'];
    }

    /**
     * Sets program_types
     *
     * @param \OpenAPI\Client\Model\SellingProgramType[]|null $program_types Модели работы магазина на Маркете.
     *
     * @return self
     */
    public function setProgramTypes($program_types)
    {
        if (is_null($program_types)) {
            array_push($this->openAPINullablesSetToNull, 'program_types');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('program_types', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }


        if (!is_null($program_types) && (count($program_types) < 1)) {
            throw new \InvalidArgumentException('invalid length for $program_types when calling GetBusinessOrdersRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['program_types'] = $program_types;

        return $this;
    }

    /**
     * Gets campaign_ids
     *
     * @return int[]|null
     */
    public function getCampaignIds()
    {
        return $this->container['campaign_ids'];
    }

    /**
     * Sets campaign_ids
     *
     * @param int[]|null $campaign_ids Идентификаторы кампаний магазинов.
     *
     * @return self
     */
    public function setCampaignIds($campaign_ids)
    {
        if (is_null($campaign_ids)) {
            array_push($this->openAPINullablesSetToNull, 'campaign_ids');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('campaign_ids', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }

        if (!is_null($campaign_ids) && (count($campaign_ids) > 50)) {
            throw new \InvalidArgumentException('invalid value for $campaign_ids when calling GetBusinessOrdersRequest., number of items must be less than or equal to 50.');
        }
        if (!is_null($campaign_ids) && (count($campaign_ids) < 1)) {
            throw new \InvalidArgumentException('invalid length for $campaign_ids when calling GetBusinessOrdersRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['campaign_ids'] = $campaign_ids;

        return $this;
    }

    /**
     * Gets statuses
     *
     * @return \OpenAPI\Client\Model\OrderStatusType[]|null
     */
    public function getStatuses()
    {
        return $this->container['statuses'];
    }

    /**
     * Sets statuses
     *
     * @param \OpenAPI\Client\Model\OrderStatusType[]|null $statuses Статусы заказов.
     *
     * @return self
     */
    public function setStatuses($statuses)
    {
        if (is_null($statuses)) {
            array_push($this->openAPINullablesSetToNull, 'statuses');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('statuses', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }


        if (!is_null($statuses) && (count($statuses) < 1)) {
            throw new \InvalidArgumentException('invalid length for $statuses when calling GetBusinessOrdersRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['statuses'] = $statuses;

        return $this;
    }

    /**
     * Gets substatuses
     *
     * @return \OpenAPI\Client\Model\OrderSubstatusType[]|null
     */
    public function getSubstatuses()
    {
        return $this->container['substatuses'];
    }

    /**
     * Sets substatuses
     *
     * @param \OpenAPI\Client\Model\OrderSubstatusType[]|null $substatuses Этапы обработки или причины отмены заказов.
     *
     * @return self
     */
    public function setSubstatuses($substatuses)
    {
        if (is_null($substatuses)) {
            array_push($this->openAPINullablesSetToNull, 'substatuses');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('substatuses', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }


        if (!is_null($substatuses) && (count($substatuses) < 1)) {
            throw new \InvalidArgumentException('invalid length for $substatuses when calling GetBusinessOrdersRequest., number of items must be greater than or equal to 1.');
        }
        $this->container['substatuses'] = $substatuses;

        return $this;
    }

    /**
     * Gets dates
     *
     * @return \OpenAPI\Client\Model\OrderDatesFilterDTO|null
     */
    public function getDates()
    {
        return $this->container['dates'];
    }

    /**
     * Sets dates
     *
     * @param \OpenAPI\Client\Model\OrderDatesFilterDTO|null $dates dates
     *
     * @return self
     */
    public function setDates($dates)
    {
        if (is_null($dates)) {
            throw new \InvalidArgumentException('non-nullable dates cannot be null');
        }
        $this->container['dates'] = $dates;

        return $this;
    }

    /**
     * Gets fake
     *
     * @return bool|null
     */
    public function getFake()
    {
        return $this->container['fake'];
    }

    /**
     * Sets fake
     *
     * @param bool|null $fake Тип заказа:  * `false` — настоящий заказ покупателя.  * `true` — [тестовый заказ](../../concepts/sandbox.md) Маркета.
     *
     * @return self
     */
    public function setFake($fake)
    {
        if (is_null($fake)) {
            throw new \InvalidArgumentException('non-nullable fake cannot be null');
        }
        $this->container['fake'] = $fake;

        return $this;
    }

    /**
     * Gets waiting_for_cancellation_approve
     *
     * @return bool|null
     */
    public function getWaitingForCancellationApprove()
    {
        return $this->container['waiting_for_cancellation_approve'];
    }

    /**
     * Sets waiting_for_cancellation_approve
     *
     * @param bool|null $waiting_for_cancellation_approve **Только для модели DBS**  Фильтр для получения заказов, по которым есть запросы на отмену.  При значении `true` возвращаются только те заказы, которые находятся в статусе `DELIVERY` или `PICKUP`, и пользователи решили их отменить.
     *
     * @return self
     */
    public function setWaitingForCancellationApprove($waiting_for_cancellation_approve)
    {
        if (is_null($waiting_for_cancellation_approve)) {
            throw new \InvalidArgumentException('non-nullable waiting_for_cancellation_approve cannot be null');
        }
        $this->container['waiting_for_cancellation_approve'] = $waiting_for_cancellation_approve;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


