<?php
/**
 * OfferCardContentStatusType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * OfferCardContentStatusType Class Doc Comment
 *
 * @category Class
 * @description Статус вычисления рейтинга карточки товара и рекомендаций:  * &#x60;UPDATING&#x60; — рейтинг обновляется. * &#x60;ACTUAL&#x60; — рейтинг актуальный.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OfferCardContentStatusType
{
    /**
     * Possible values of this enum
     */
    public const UPDATING = 'UPDATING';

    public const ACTUAL = 'ACTUAL';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::UPDATING,
            self::ACTUAL
        ];
    }
}


