<?php
/**
 * OrderItemUnitStatusType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * OrderItemUnitStatusType Class Doc Comment
 *
 * @category Class
 * @description Статус единицы товара в заказе.  * &#x60;CREATED&#x60; — создана.  * &#x60;SHIPPED&#x60; — передана в доставку.  * &#x60;CANCELLED&#x60; — отменена или удалена из заказа.  * &#x60;DELIVERED_TO_BUYER&#x60; — передана покупателю.  * &#x60;LOST&#x60; — утеряна.  * &#x60;REJECTED&#x60; — невыкупленная.  * &#x60;RETURNED&#x60; — возвращенная.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class OrderItemUnitStatusType
{
    /**
     * Possible values of this enum
     */
    public const CREATED = 'CREATED';

    public const SHIPPED = 'SHIPPED';

    public const CANCELLED = 'CANCELLED';

    public const DELIVERED_TO_BUYER = 'DELIVERED_TO_BUYER';

    public const LOST = 'LOST';

    public const REJECTED = 'REJECTED';

    public const RETURNED = 'RETURNED';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::CREATED,
            self::SHIPPED,
            self::CANCELLED,
            self::DELIVERED_TO_BUYER,
            self::LOST,
            self::REJECTED,
            self::RETURNED
        ];
    }
}


