<?php
/**
 * PromoOfferBestPriceLevelsDTO
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * PromoOfferBestPriceLevelsDTO Class Doc Comment
 *
 * @category Class
 * @description Максимальные цены для участия в акции «Бестселлеры Маркета» по уровням:  * **Лайт-бестселлер** — &#x60;lightBestLevel&#x60; * **Бестселлер** — &#x60;bestLevel&#x60; * **Супербестселлер** — &#x60;superBestLevel&#x60; * **Топ-бестселлер** — &#x60;topBestLevel&#x60;  Чтобы товар участвовал на определенном уровне, цена по акции должна быть не выше порога этого уровня.  Параметр возвращается только для акций «Бестселлеры Маркета». Подробнее об этой акции читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/marketing/promos/market/bestsellers).
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PromoOfferBestPriceLevelsDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'PromoOfferBestPriceLevelsDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'light_best_level' => 'int',
        'best_level' => 'int',
        'super_best_level' => 'int',
        'top_best_level' => 'int'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'light_best_level' => 'int64',
        'best_level' => 'int64',
        'super_best_level' => 'int64',
        'top_best_level' => 'int64'
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'light_best_level' => false,
        'best_level' => false,
        'super_best_level' => false,
        'top_best_level' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'light_best_level' => 'lightBestLevel',
        'best_level' => 'bestLevel',
        'super_best_level' => 'superBestLevel',
        'top_best_level' => 'topBestLevel'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'light_best_level' => 'setLightBestLevel',
        'best_level' => 'setBestLevel',
        'super_best_level' => 'setSuperBestLevel',
        'top_best_level' => 'setTopBestLevel'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'light_best_level' => 'getLightBestLevel',
        'best_level' => 'getBestLevel',
        'super_best_level' => 'getSuperBestLevel',
        'top_best_level' => 'getTopBestLevel'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('light_best_level', $data ?? [], null);
        $this->setIfExists('best_level', $data ?? [], null);
        $this->setIfExists('super_best_level', $data ?? [], null);
        $this->setIfExists('top_best_level', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['light_best_level'] === null) {
            $invalidProperties[] = "'light_best_level' can't be null";
        }
        if ($this->container['best_level'] === null) {
            $invalidProperties[] = "'best_level' can't be null";
        }
        if ($this->container['super_best_level'] === null) {
            $invalidProperties[] = "'super_best_level' can't be null";
        }
        if ($this->container['top_best_level'] === null) {
            $invalidProperties[] = "'top_best_level' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets light_best_level
     *
     * @return int
     */
    public function getLightBestLevel()
    {
        return $this->container['light_best_level'];
    }

    /**
     * Sets light_best_level
     *
     * @param int $light_best_level Максимальная цена для участия на уровне **Лайт-бестселлер**.  Указывается в рублях.
     *
     * @return self
     */
    public function setLightBestLevel($light_best_level)
    {
        if (is_null($light_best_level)) {
            throw new \InvalidArgumentException('non-nullable light_best_level cannot be null');
        }
        $this->container['light_best_level'] = $light_best_level;

        return $this;
    }

    /**
     * Gets best_level
     *
     * @return int
     */
    public function getBestLevel()
    {
        return $this->container['best_level'];
    }

    /**
     * Sets best_level
     *
     * @param int $best_level Максимальная цена для участия на уровне **Бестселлер**.  Указывается в рублях.
     *
     * @return self
     */
    public function setBestLevel($best_level)
    {
        if (is_null($best_level)) {
            throw new \InvalidArgumentException('non-nullable best_level cannot be null');
        }
        $this->container['best_level'] = $best_level;

        return $this;
    }

    /**
     * Gets super_best_level
     *
     * @return int
     */
    public function getSuperBestLevel()
    {
        return $this->container['super_best_level'];
    }

    /**
     * Sets super_best_level
     *
     * @param int $super_best_level Максимальная цена для участия на уровне **Супербестселлер**.  Указывается в рублях.
     *
     * @return self
     */
    public function setSuperBestLevel($super_best_level)
    {
        if (is_null($super_best_level)) {
            throw new \InvalidArgumentException('non-nullable super_best_level cannot be null');
        }
        $this->container['super_best_level'] = $super_best_level;

        return $this;
    }

    /**
     * Gets top_best_level
     *
     * @return int
     */
    public function getTopBestLevel()
    {
        return $this->container['top_best_level'];
    }

    /**
     * Sets top_best_level
     *
     * @param int $top_best_level Максимальная цена для участия на уровне **Топ-бестселлер**.  Указывается в рублях.
     *
     * @return self
     */
    public function setTopBestLevel($top_best_level)
    {
        if (is_null($top_best_level)) {
            throw new \InvalidArgumentException('non-nullable top_best_level cannot be null');
        }
        $this->container['top_best_level'] = $top_best_level;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


