<?php
/**
 * ReturnAvailableDecisionDTO
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * ReturnAvailableDecisionDTO Class Doc Comment
 *
 * @category Class
 * @description Доступное решение по возврату.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class ReturnAvailableDecisionDTO implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ReturnAvailableDecisionDTO';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'decision_type' => '\OpenAPI\Client\Model\ReturnDecisionType',
        'decision_reason_types' => '\OpenAPI\Client\Model\ReturnRequestDecisionReasonType[]',
        'partial_compensation_bounds' => '\OpenAPI\Client\Model\PartialCompensationBoundsDTO'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'decision_type' => null,
        'decision_reason_types' => null,
        'partial_compensation_bounds' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'decision_type' => false,
        'decision_reason_types' => true,
        'partial_compensation_bounds' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'decision_type' => 'decisionType',
        'decision_reason_types' => 'decisionReasonTypes',
        'partial_compensation_bounds' => 'partialCompensationBounds'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'decision_type' => 'setDecisionType',
        'decision_reason_types' => 'setDecisionReasonTypes',
        'partial_compensation_bounds' => 'setPartialCompensationBounds'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'decision_type' => 'getDecisionType',
        'decision_reason_types' => 'getDecisionReasonTypes',
        'partial_compensation_bounds' => 'getPartialCompensationBounds'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('decision_type', $data ?? [], null);
        $this->setIfExists('decision_reason_types', $data ?? [], null);
        $this->setIfExists('partial_compensation_bounds', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['decision_type'] === null) {
            $invalidProperties[] = "'decision_type' can't be null";
        }
        if (!is_null($this->container['decision_reason_types']) && (count($this->container['decision_reason_types']) < 1)) {
            $invalidProperties[] = "invalid value for 'decision_reason_types', number of items must be greater than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets decision_type
     *
     * @return \OpenAPI\Client\Model\ReturnDecisionType
     */
    public function getDecisionType()
    {
        return $this->container['decision_type'];
    }

    /**
     * Sets decision_type
     *
     * @param \OpenAPI\Client\Model\ReturnDecisionType $decision_type decision_type
     *
     * @return self
     */
    public function setDecisionType($decision_type)
    {
        if (is_null($decision_type)) {
            throw new \InvalidArgumentException('non-nullable decision_type cannot be null');
        }
        $this->container['decision_type'] = $decision_type;

        return $this;
    }

    /**
     * Gets decision_reason_types
     *
     * @return \OpenAPI\Client\Model\ReturnRequestDecisionReasonType[]|null
     */
    public function getDecisionReasonTypes()
    {
        return $this->container['decision_reason_types'];
    }

    /**
     * Sets decision_reason_types
     *
     * @param \OpenAPI\Client\Model\ReturnRequestDecisionReasonType[]|null $decision_reason_types Возможные причины отказа (только для решения DECLINE_REFUND).
     *
     * @return self
     */
    public function setDecisionReasonTypes($decision_reason_types)
    {
        if (is_null($decision_reason_types)) {
            array_push($this->openAPINullablesSetToNull, 'decision_reason_types');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('decision_reason_types', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }


        if (!is_null($decision_reason_types) && (count($decision_reason_types) < 1)) {
            throw new \InvalidArgumentException('invalid length for $decision_reason_types when calling ReturnAvailableDecisionDTO., number of items must be greater than or equal to 1.');
        }
        $this->container['decision_reason_types'] = $decision_reason_types;

        return $this;
    }

    /**
     * Gets partial_compensation_bounds
     *
     * @return \OpenAPI\Client\Model\PartialCompensationBoundsDTO|null
     */
    public function getPartialCompensationBounds()
    {
        return $this->container['partial_compensation_bounds'];
    }

    /**
     * Sets partial_compensation_bounds
     *
     * @param \OpenAPI\Client\Model\PartialCompensationBoundsDTO|null $partial_compensation_bounds partial_compensation_bounds
     *
     * @return self
     */
    public function setPartialCompensationBounds($partial_compensation_bounds)
    {
        if (is_null($partial_compensation_bounds)) {
            throw new \InvalidArgumentException('non-nullable partial_compensation_bounds cannot be null');
        }
        $this->container['partial_compensation_bounds'] = $partial_compensation_bounds;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


