<?php
/**
 * VatRateType
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;
use \OpenAPI\Client\ObjectSerializer;

/**
 * VatRateType Class Doc Comment
 *
 * @category Class
 * @description Ставка НДС. Возможные значения:  * &#x60;VAT_22&#x60; — НДС 22%. * &#x60;NO_VAT&#x60; — НДС не облагается. * &#x60;VAT_12&#x60; — НДС 12%. * &#x60;VAT_10&#x60; — НДС 10%. * &#x60;VAT_05&#x60; — НДС 5%. * &#x60;VAT_07&#x60; — НДС 7%.  Если у партнёра в кабинете установлена ставка, не входящая в список, — значение не возвращается.
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class VatRateType
{
    /**
     * Possible values of this enum
     */
    public const VAT_22 = 'VAT_22';

    public const NO_VAT = 'NO_VAT';

    public const VAT_12 = 'VAT_12';

    public const VAT_10 = 'VAT_10';

    public const VAT_05 = 'VAT_05';

    public const VAT_07 = 'VAT_07';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::VAT_22,
            self::NO_VAT,
            self::VAT_12,
            self::VAT_10,
            self::VAT_05,
            self::VAT_07
        ];
    }
}


