<?php
/**
 * DigitalGoodsDeliveryTypeTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DigitalGoodsDeliveryTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Способ получения цифрового товара:  * &#x60;EMAIL&#x60; — код активации по почте: покупатель получит письмо с кодом и инструкцией на почту.  * &#x60;ACTIVATION_CODE&#x60; — код активации в заказе на Маркете: покупатель получит инструкцию и код в чате с магазином, а в списке заказов сможет скопировать код.  * &#x60;STEAM_GIFT&#x60; — игры подарком в Steam: вы получите от покупателя ссылку формата https://s.team/p/m**-***_/_******** на добавление в друзья. Перейдите по ссылке, добавьте покупателя в друзья и отправьте ему игру. В течение трех часов передайте Маркету статус, что заказ доставлен — через API или на странице заказа.  * &#x60;CHAT&#x60; — игры и товары в чате с покупателем на Маркете: покупатель получит сертификат в чате с магазином. Передайте Маркету статус, что заказ доставлен — через API или на странице заказа.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DigitalGoodsDeliveryTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DigitalGoodsDeliveryType"
     */
    public function testDigitalGoodsDeliveryType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
