<?php
/**
 * DocumentErrorCodeTypeTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DocumentErrorCodeTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Код ошибки документа:  * &#x60;DOCUMENT_VALIDATION_FAILED&#x60; — документ не прошел проверку. * &#x60;DOCUMENT_ALREADY_EXISTS&#x60; — документ уже существует. * &#x60;DOCUMENT_NOT_FOUND&#x60; — документ не найден. * &#x60;DOCUMENT_UPDATE_NOT_ALLOWED&#x60; — изменение документа запрещено. * &#x60;DOCUMENT_CONCURRENT_MODIFICATION&#x60; — документ был изменен параллельно.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DocumentErrorCodeTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DocumentErrorCodeType"
     */
    public function testDocumentErrorCodeType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
