<?php
/**
 * DocumentTypeTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * DocumentTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Тип документа:  * &#x60;CONFORMITY_DECLARATION&#x60; — Декларация о соответствии. * &#x60;CONFORMITY_CERTIFICATE&#x60; — Сертификат соответствия. * &#x60;STATE_REGISTRATION_CERTIFICATE&#x60; — Государственная регистрация продукции (санэпид требования). * &#x60;MEDICINAL_PRODUCT_CERTIFICATE&#x60; — Обязательные документы для аптеки. * &#x60;BIOLOGICALLY_ACTIVE_ADDITIVE_CERTIFICATE&#x60; — Свидетельство о государственной регистрации БАД. * &#x60;MEDICAL_DEVICE_CERTIFICATE&#x60; — Регистрационное удостоверение медицинского изделия. * &#x60;AGROCHEMICAL_PESTICIDE_CERTIFICATE&#x60; — Государственная регистрация пестицида и агрохимиката.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class DocumentTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "DocumentType"
     */
    public function testDocumentType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
