<?php
/**
 * ItemPriceDTOTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ItemPriceDTOTest Class Doc Comment
 *
 * @category    Class
 * @description Информация о выплатах и вознаграждениях.  {% note info \&quot;Как рассчитывается стоимость всех единиц товара и вознаграждение продавцу\&quot; %}  * Стоимость всех единиц товара складывается из параметров &#x60;payment&#x60; и &#x60;cashback&#x60;. * Общая сумма вознаграждений продавцу возвращается в параметре &#x60;subsidy&#x60;. * Значение &#x60;payment&#x60;, &#x60;cashback&#x60; и &#x60;subsidy&#x60; может отличаться от стоимости в каталоге, потому что информация об акциях магазина не возвращается. * Если в заказе несколько единиц товаров, в параметрах возвращается суммарное значение. * Все суммы указаны в валюте магазина.  {% endnote %}
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ItemPriceDTOTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ItemPriceDTO"
     */
    public function testItemPriceDTO()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payment"
     */
    public function testPropertyPayment()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "subsidy"
     */
    public function testPropertySubsidy()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "cashback"
     */
    public function testPropertyCashback()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "vat"
     */
    public function testPropertyVat()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
