<?php
/**
 * OrderItemUnitStatusTypeTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * OrderItemUnitStatusTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Статус единицы товара в заказе.  * &#x60;CREATED&#x60; — создана.  * &#x60;SHIPPED&#x60; — передана в доставку.  * &#x60;CANCELLED&#x60; — отменена или удалена из заказа.  * &#x60;DELIVERED_TO_BUYER&#x60; — передана покупателю.  * &#x60;LOST&#x60; — утеряна.  * &#x60;REJECTED&#x60; — невыкупленная.  * &#x60;RETURNED&#x60; — возвращенная.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class OrderItemUnitStatusTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OrderItemUnitStatusType"
     */
    public function testOrderItemUnitStatusType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
