<?php
/**
 * PromoOfferBestPriceLevelsDTOTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * PromoOfferBestPriceLevelsDTOTest Class Doc Comment
 *
 * @category    Class
 * @description Максимальные цены для участия в акции «Бестселлеры Маркета» по уровням:  * **Лайт-бестселлер** — &#x60;lightBestLevel&#x60; * **Бестселлер** — &#x60;bestLevel&#x60; * **Супербестселлер** — &#x60;superBestLevel&#x60; * **Топ-бестселлер** — &#x60;topBestLevel&#x60;  Чтобы товар участвовал на определенном уровне, цена по акции должна быть не выше порога этого уровня.  Параметр возвращается только для акций «Бестселлеры Маркета». Подробнее об этой акции читайте [в Справке Маркета для продавцов](https://yandex.ru/support2/marketplace/ru/marketing/promos/market/bestsellers).
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PromoOfferBestPriceLevelsDTOTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PromoOfferBestPriceLevelsDTO"
     */
    public function testPromoOfferBestPriceLevelsDTO()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "light_best_level"
     */
    public function testPropertyLightBestLevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "best_level"
     */
    public function testPropertyBestLevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "super_best_level"
     */
    public function testPropertySuperBestLevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "top_best_level"
     */
    public function testPropertyTopBestLevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
