<?php
/**
 * RefundStatusTypeTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RefundStatusTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Статус возврата денег:  * &#x60;STARTED_BY_USER&#x60; — создан клиентом из личного кабинета.  * &#x60;REFUND_IN_PROGRESS&#x60; — ждет решение о возврате денег.  * &#x60;REFUNDED&#x60; — деньги возвращены.  * &#x60;FAILED&#x60; — невозможно провести возврат покупателю.  * &#x60;WAITING_FOR_DECISION&#x60; — ожидает решения (:no-translate[DBS]).  * &#x60;DECISION_MADE&#x60; — по возврату принято решение (:no-translate[DBS]).  * &#x60;REFUNDED_WITH_BONUSES&#x60; — возврат осуществлен баллами Плюса или промокодом.  * &#x60;REFUNDED_BY_SHOP&#x60; — магазин сделал самостоятельно возврат денег.  * &#x60;COMPLETE_WITHOUT_REFUND&#x60; — возврат денег не требуется.  * &#x60;CANCELLED&#x60; — возврат отменен.  * &#x60;REJECTED&#x60; — возврат отклонен модерацией или в ПВЗ.  * &#x60;PREMODERATION_DISPUTE&#x60; — по возврату открыт спор (:no-translate[FBS] и Экспресс).  * &#x60;PREMODERATION_DECISION_WAITING&#x60; — ожидает решения (:no-translate[FBS] и Экспресс).  * &#x60;PREMODERATION_DECISION_MADE&#x60; — по возврату принято решение (:no-translate[FBS] и Экспресс).  * &#x60;PREMODERATION_SELECT_DELIVERY&#x60; — пользователь выбирает способ доставки (:no-translate[FBS] и Экспресс).  * &#x60;UNKNOWN&#x60; — неизвестный статус.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RefundStatusTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RefundStatusType"
     */
    public function testRefundStatusType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
