<?php
/**
 * SupplyRequestSortAttributeTypeTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SupplyRequestSortAttributeTypeTest Class Doc Comment
 *
 * @category    Class
 * @description По какому параметру сортировать заявки:  * &#x60;ID&#x60; — идентификатор заявки. * &#x60;REQUESTED_DATE&#x60; — дата поставки на склад хранения.      Если товары проходили через транзитный склад, сортирует по датам поставки на оба склада. * &#x60;UPDATED_AT&#x60; — время обновления заявки. * &#x60;STATUS&#x60; — статус заявки.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SupplyRequestSortAttributeTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SupplyRequestSortAttributeType"
     */
    public function testSupplyRequestSortAttributeType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
