<?php
/**
 * SupplyRequestStatusTypeTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * SupplyRequestStatusTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Статус заявки на поставку:  * &#x60;CREATED&#x60; — создан черновик заявки. * &#x60;FINISHED&#x60; — заявка завершена, товары:   * приняты на складе;   * переданы на другой склад при перемещении;   * переданы продавцу при вывозе;   * утилизированы. * &#x60;CANCELLED&#x60; — заявка отменена. * &#x60;INVALID&#x60; — ошибка обработки. * &#x60;VALIDATED&#x60; — заявка в обработке. * &#x60;PUBLISHED&#x60; — создана заявка. * &#x60;ARRIVED_TO_SERVICE&#x60; — поставка прибыла на склад хранения. * &#x60;ARRIVED_TO_XDOC_SERVICE&#x60; — поставка прибыла на транзитный склад. * &#x60;SHIPPED_TO_SERVICE&#x60; — поставка отправлена с транзитного склада на склад хранения. * &#x60;CANCELLATION_REQUESTED&#x60; — запрошена отмена заявки. * &#x60;CANCELLATION_REJECTED&#x60; — заявка не будет отменена. * &#x60;REGISTERED_IN_ELECTRONIC_QUEUE&#x60; — поставка зарегистрирована в электронной очереди. * &#x60;READY_FOR_UTILIZATION&#x60; — товары готовы к утилизации. * &#x60;TRANSIT_MOVING&#x60; — перемещение товаров на склад вывоза. * &#x60;WAREHOUSE_HANDLING&#x60; — вторичная приемка товаров или их сборка для вывоза или утилизации. * &#x60;ACCEPTED_BY_WAREHOUSE_SYSTEM&#x60; — информация о заявке направлена на склад. * &#x60;READY_TO_WITHDRAW&#x60; — товары готовы к выдаче.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SupplyRequestStatusTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SupplyRequestStatusType"
     */
    public function testSupplyRequestStatusType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
