<?php
/**
 * VatRateTypeTest
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace OpenAPI\Client\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * VatRateTypeTest Class Doc Comment
 *
 * @category    Class
 * @description Ставка НДС. Возможные значения:  * &#x60;VAT_22&#x60; — НДС 22%. * &#x60;NO_VAT&#x60; — НДС не облагается. * &#x60;VAT_12&#x60; — НДС 12%. * &#x60;VAT_10&#x60; — НДС 10%. * &#x60;VAT_05&#x60; — НДС 5%. * &#x60;VAT_07&#x60; — НДС 7%.  Если у партнёра в кабинете установлена ставка, не входящая в список, — значение не возвращается.
 * @package     OpenAPI\Client
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class VatRateTypeTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "VatRateType"
     */
    public function testVatRateType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
