<?php
/**
 * ReportsApiTest
 * PHP version 8.1
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * API Яндекс Маркета для продавцов
 *
 * API Яндекс Маркета помогает продавцам автоматизировать и упростить работу с маркетплейсом.  В числе возможностей интеграции:  * управление каталогом товаров и витриной,  * обработка заказов,  * изменение настроек магазина,  * получение отчетов.
 *
 * The version of the OpenAPI document: LATEST
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.18.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace OpenAPI\Client\Test\Api;

use \OpenAPI\Client\Configuration;
use \OpenAPI\Client\ApiException;
use \OpenAPI\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReportsApiTest Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReportsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for generateBannersStatisticsReport
     *
     * Отчет по охватному продвижению.
     *
     */
    public function testGenerateBannersStatisticsReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateBarcodesReport
     *
     * Получение файла со штрихкодами.
     *
     */
    public function testGenerateBarcodesReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateBoostConsolidatedReport
     *
     * Отчет по бусту продаж.
     *
     */
    public function testGenerateBoostConsolidatedReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateClosureDocumentsDetalizationReport
     *
     * Отчет по схождению с закрывающими документами.
     *
     */
    public function testGenerateClosureDocumentsDetalizationReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateClosureDocumentsReport
     *
     * Закрывающие документы.
     *
     */
    public function testGenerateClosureDocumentsReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateCompetitorsPositionReport
     *
     * Отчет «Конкурентная позиция».
     *
     */
    public function testGenerateCompetitorsPositionReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateGoodsFeedbackReport
     *
     * Отчет по отзывам о товарах.
     *
     */
    public function testGenerateGoodsFeedbackReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateGoodsMovementReport
     *
     * Отчет по движению товаров.
     *
     */
    public function testGenerateGoodsMovementReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateGoodsPricesReport
     *
     * Отчет «Цены».
     *
     */
    public function testGenerateGoodsPricesReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateGoodsRealizationReport
     *
     * Отчет по реализации.
     *
     */
    public function testGenerateGoodsRealizationReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateGoodsTurnoverReport
     *
     * Отчет по оборачиваемости.
     *
     */
    public function testGenerateGoodsTurnoverReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateJewelryFiscalReport
     *
     * Отчет по заказам с ювелирными изделиями.
     *
     */
    public function testGenerateJewelryFiscalReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateKeyIndicatorsReport
     *
     * Отчет по ключевым показателям.
     *
     */
    public function testGenerateKeyIndicatorsReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateMassOrderLabelsReport
     *
     * Готовые ярлыки‑наклейки на все коробки в нескольких заказах.
     *
     */
    public function testGenerateMassOrderLabelsReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generatePricesReport
     *
     * Отчет «Цены на рынке».
     *
     */
    public function testGeneratePricesReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateSalesGeographyReport
     *
     * Отчет по географии продаж.
     *
     */
    public function testGenerateSalesGeographyReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateShelfsStatisticsReport
     *
     * Отчет по полкам.
     *
     */
    public function testGenerateShelfsStatisticsReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateShipmentListDocumentReport
     *
     * Получение листа сборки.
     *
     */
    public function testGenerateShipmentListDocumentReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateShowsBoostReport
     *
     * Отчет по бусту показов.
     *
     */
    public function testGenerateShowsBoostReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateShowsSalesReport
     *
     * Отчет «Аналитика продаж».
     *
     */
    public function testGenerateShowsSalesReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateStocksOnWarehousesReport
     *
     * Отчет по остаткам на складах.
     *
     */
    public function testGenerateStocksOnWarehousesReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateUnitedMarketplaceServicesReport
     *
     * Отчет по стоимости услуг.
     *
     */
    public function testGenerateUnitedMarketplaceServicesReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateUnitedNettingReport
     *
     * Отчет по платежам.
     *
     */
    public function testGenerateUnitedNettingReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateUnitedOrdersReport
     *
     * Отчет по заказам.
     *
     */
    public function testGenerateUnitedOrdersReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for generateUnitedReturnsReport
     *
     * Отчет по невыкупам и возвратам.
     *
     */
    public function testGenerateUnitedReturnsReport()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getReportInfo
     *
     * Получение заданного отчета или документа.
     *
     */
    public function testGetReportInfo()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
